version: '3.1'

services:
  il2stats-web:
    build: .
    environment:
      ADMIN_EMAIL: your@email.com
      ADMIN_PASSWORD: 123qwe*
    ports:
      - 8081:8080
    networks:
      database:
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    container_name: il2stats-web
    depends_on:
      - db
    volumes:
      - /mnt/il2/:/user/local/il2gamefolder:ro
      # - ./il2stats_conf.ini:/user/local/il2_stats/src/conf.ini:ro


  db:
    image: "postgres"
    environment:
      POSTGRES_PASSWORD: 123qwe*
      POSTGRES_USER: il2_stats
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "16542:5432"
    networks:
      database:
    container_name: postgres
    volumes:
      - ~/il2stats_db:/var/lib/postgresql/data/pgdata:rw
    
  # pgadmin:
  #   image: dpage/pgadmin4
  #   container_name: pgadmin
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: your@email.com
  #     PGADMIN_DEFAULT_PASSWORD: 123qwe*
  #     DEFAULT_SERVER_PORT: 5050
  #   ports:
  #     - "16543:80"
  #   depends_on:
  #     - db
  #   networks:
  #     database:
  #   # volumes:
  #     # - /mnt/d/Users/Eux/Documents/il2stats_pgadmin:/var/lib/pgadmin:rw

networks:
  database:
    